# [target.thumbv7m-none-eabi]
# # uncomment this to make `cargo run` execute programs on QEMU
# # runner = "qemu-system-arm -cpu cortex-m3 -machine lm3s6965evb -nographic -semihosting-config enable=on,target=native -kernel"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "gdb-multiarch -q -x openocd.gdb"

[build]
target = "thumbv7em-none-eabihf"       # Cortex-M4F